### ISSUE TITLE
"Command failed :" [...] "too many positional arguments"

### ISSUE THREAD

**Issue by Ilshidur** [meryn/mongo-utils#4]
Running on Windows 10. I'm having the following error :

> Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "mongorestore '--db' 'championgg' '--drop' './championweb/db/championgg/'"
> 2016-03-13T02:42:33.659+0100    too many positional arguments
> 2016-03-13T02:42:33.660+0100    try 'mongorestore --help' for more information

=> mongo-utils runs this command `mongorestore '--db' 'championgg' '--drop' './championweb/db/championgg/` : it fails ("too many positional arguments").

The code creating the arguments ([function "makeArgumentString"](https://github.com/myrne/mongo-utils/blob/master/src/utils.coffee#L122)) adds two additional single quotes for each one of them.

=> If I run `mongorestore --db championgg --drop ./championweb/db/championgg/` (without the single quotes) : the command runs successfully.

How can I fix this problem ?

**Comment by landorg** [comment]
+1
